/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6progra2;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class IngresarDocente extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresarDocente
     */
    public IngresarDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioDocente = new javax.swing.JLabel();
        lblContraDocente = new javax.swing.JLabel();
        ptxtContraDocente = new javax.swing.JPasswordField();
        txtUsarioDocente = new javax.swing.JTextField();
        btnIngresarDocente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ingresar");

        lblUsuarioDocente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuarioDocente.setText("Usuario:");

        lblContraDocente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblContraDocente.setText("Contra:");

        ptxtContraDocente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtUsarioDocente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnIngresarDocente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIngresarDocente.setText("Ingresar");
        btnIngresarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresarDocente)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraDocente)
                            .addComponent(lblUsuarioDocente))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsarioDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(ptxtContraDocente))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioDocente)
                    .addComponent(txtUsarioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraDocente)
                    .addComponent(ptxtContraDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnIngresarDocente)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarDocenteActionPerformed
        // TODO add your handling code here:
        //Usuarios Default
        String [] Docentes ={"javier","alexis"};
        String [] ContrasDocentes =new String[2];
        ContrasDocentes[0]="hola"; //clave javier
        ContrasDocentes[1]="qp2"; //clave jose
        
        //Validacion
        String usuario=txtUsarioDocente.getText();
        String contrasena=ptxtContraDocente.getText();
        
        boolean mensaje=false;
        
        for(int i=0;i<Docentes.length;i++){
            if(Docentes[i].equals(usuario) && ContrasDocentes[i].equals(contrasena)){
                mensaje=true;
            }
        }
        if(mensaje){
            Principal frm=new Principal();
            frm.setVisible(true);
            JOptionPane.showMessageDialog(null,"Bienvenido");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Intente de nuevo");
            txtUsarioDocente.setText("");
            ptxtContraDocente.setText("");
        }
    }//GEN-LAST:event_btnIngresarDocenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarDocente;
    private javax.swing.JLabel lblContraDocente;
    private javax.swing.JLabel lblUsuarioDocente;
    private javax.swing.JPasswordField ptxtContraDocente;
    private javax.swing.JTextField txtUsarioDocente;
    // End of variables declaration//GEN-END:variables
}
